### ISSUE TITLE
Traceur fails when using retry

### ISSUE THREAD

**Issue by mkoslacz** [T-Spoon/Traceur#1]
Hi, 

I have encountered a bug when you use `Observable.retry()` with a Traceur logging on. There is a `java.lang.IllegalArgumentException: Self-causation not permitted` in such case.

I have created a gist that showcases the issue, it's available [here](https://gist.github.com/mkoslacz/50e1be76cf41b9806c03f3f5d28ab4b1).

Best regards,

Mateusz

**Comment by T-Spoon** [comment]
Hey - thanks for the test case!

Added it to the repo and fixed the issue - you should be able to get the fix by using:

`compile 'com.tspoon.traceur:traceur:1.0.1'`

**Comment by mkoslacz** [comment]
Yep, now it works correctly. Thanks!
